### ISSUE TITLE
Table name already exists

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#717]
LLM generated table name could be duplicate of previous and when recreating the eph table, it crashes:

```python
  File "/Users/ahuang/repos/lumen/lumen/ai/assistant.py", line 482, in invoke
    await agent.invoke(messages[-context_length:], **kwargs)
  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 738, in invoke
    sql_query = await self.answer(messages)
  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 734, in answer
    sql_query = await self._create_valid_sql(messages, system, tables_to_source)
  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 47, in async_wrapper
    output = await func(*args, **kwargs)
  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 606, in _create_valid_sql
    raise e
  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 580, in _create_valid_sql
    sql_expr_source = source.create_sql_expr_source({expr_slug: sql_query})
  File "/Users/ahuang/repos/lumen/lumen/sources/duckdb.py", line 232, in create_sql_expr_source
    raise e
  File "/Users/ahuang/repos/lumen/lumen/sources/duckdb.py", line 217, in create_sql_expr_source
    self._connection.execute(table_expr)
duckdb.duckdb.CatalogException: Catalog Error: Table with name "top_5_winter_olympic_games" already exists
```

**Comment by philippjfr** [comment]
Can we agree to record the dataset and prompt that generated a particular error.

**Comment by ahuang11** [comment]
Will close for now; can't reproduce and it should theoretically be handled:
```

            if table in existing or sql_expr == self.sql_expr.format(table=f'"{table}"'):
                continue
```

**Comment by ahuang11** [comment]
<img width="685" alt="Image" src="https://github.com/user-attachments/assets/6a34bd43-3f07-4129-b2e3-c373a02724f8" />


Encountered this again

Data:
[data.zip](https://github.com/user-attachments/files/18263422/data.zip)

```
Traceback (most recent call last):

  File "/Users/ahuang/repos/lumen/lumen/sources/duckdb.py", line 218, in create_sql_expr_source
    self._connection.execute(table_expr)

duckdb.duckdb.CatalogException: Catalog Error: Table with name "min_max_airfare_values" already exists!


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/ahuang/repos/lumen/lumen/ai/coordinator.py", line 421, in _execute_graph_node
    result = await subagent.respond(
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 744, in respond
    sql_query = await self._create_valid_sql(messages, system_prompt, tables_to_source, step_title)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 110, in async_wrapper
    raise e

  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 104, in async_wrapper
    output = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 580, in _create_valid_sql
    raise e

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 571, in _create_valid_sql
    sql_expr_source = source.create_sql_expr_source({expr_slug: sql_query})
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/sources/duckdb.py", line 224, in create_sql_expr_source
    real = self.tables[name] if name in self.tables else self.tables[name.strip('"')]
                                                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^

KeyError: 'min_max_airfare_values'
```

**Comment by ahuang11** [comment]
Still encountering this

<img width="706" alt="Image" src="https://github.com/user-attachments/assets/9a0641b3-bb60-4694-8aab-fe54a4b0927d" />

```python
Traceback (most recent call last):

  File "/Users/ahuang/repos/lumen/lumen/sources/duckdb.py", line 218, in create_sql_expr_source
    self._connection.execute(table_expr)

duckdb.duckdb.CatalogException: Catalog Error: Table with name "average_delay_by_carrier" already exists!


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/ahuang/repos/lumen/lumen/ai/coordinator.py", line 421, in _execute_graph_node
    result = await subagent.respond(
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 753, in respond
    sql_query = await self._create_valid_sql(messages, system_prompt, tables_to_source, step_title)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 110, in async_wrapper
    raise e

  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 104, in async_wrapper
    output = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 587, in _create_valid_sql
    raise e

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 578, in _create_valid_sql
    sql_expr_source = source.create_sql_expr_source({expr_slug: sql_query})
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/sources/duckdb.py", line 224, in create_sql_expr_source
    real = self.tables[name] if name in self.tables else self.tables[name.strip('"')]
                                                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^

KeyError: 'average_delay_by_carrier'
```
