### ISSUE TITLE
First run errors

### ISSUE THREAD

**Issue by amaloney** [holoviz/lumen#758]
#### ALL software version info

<details>
    <summary>Software Version Info</summary>

```plaintext
Python 3.12.7
Panel 1.5.4
panel-graphic-walker 0.5.0
lumen[ai-llama,sql] 0.7.0a35
```
</details>

#### Description of expected behavior and the observed behavior

- **Expected behavior** was to use a local LLM to with penguin data.
- **Observed behavior** was errors shown in the stack traces below.

#### Complete, minimal, self-contained example code that reproduces the issue

Use the following environment file to install a `conda` environment, and activate it.

```yaml
# environment.yaml
name: lumen-ai
channels:
    - conda-forge
dependencies:
    - pip
    - python >3.9,<3.13
    - pip:
        - lumen[ai-llama,sql] ==0.7.0a35
        - panel ==1.5.4
        - panel-graphic-walker[kernel]
```

```bash
conda env create --file environment.yaml && conda activate lumen-ai
```

Then run the `app.py` file below using `panel`.

```python
# app.py
import lumen.ai as lmai
llm = lmai.llm.Llama()
lmai.ExplorerUI(["./penguins.csv"], llm=llm, agents=[lmai.agents.VegaLiteAgent]).servable()
```

```bash
panel serve app.py --show
```

#### Stack traceback and/or browser JavaScript console output

```python
Traceback (most recent call last):

  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/coordinator.py", line 648, in _compute_execution_graph
    plan = await self._make_plan(
           ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/coordinator.py", line 566, in _make_plan
    async for reasoning in self.llm.stream(

  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/llm.py", line 120, in stream
    chunks = await self.invoke(
             ^^^^^^^^^^^^^^^^^^

  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/llm.py", line 88, in invoke
    output = await self.run_client(model_key, messages, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/llm.py", line 206, in run_client
    return await client(messages=messages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: object generator can't be used in 'await' expression
```

```python
Traceback (most recent call last):
  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/panel/chat/feed.py", line 566, in _prepare_response
    await asyncio.gather(
  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/panel/chat/feed.py", line 533, in _handle_callback
    response = await self.callback(*callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/ui.py", line 345, in wrapper
    await callback(contents, user, instance)
  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/coordinator.py", line 343, in _chat_invoke
    await self.respond(contents)
  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/coordinator.py", line 425, in respond
    execution_graph = await self._compute_execution_graph(messages[-context_length:], agents)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/lumen-ai/lib/python3.12/site-packages/lumen/ai/coordinator.py", line 661, in _compute_execution_graph
    return execution_graph[::-1]
           ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'execution_graph' where it is not associated with a value
```

#### Screenshots or screencasts of the bug in action

![Image](https://github.com/user-attachments/assets/67087312-ff5c-4f50-87db-94c560418f20)

- [x] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Seems to have been caused because the Llama implementation assumes the wrapper is asynchronous when Llama only provides a synchronous completion API.
