### ISSUE TITLE
Step is None?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#864]
```
SQL agent is working on the following task:

Generate and execute a query to group the data by month and calculate the average number of passengers from the 'passengers.csv' table.

Traceback (most recent call last):

  File "/Users/ahuang/repos/lumen/lumen/ai/coordinator.py", line 407, in _execute_graph_node
    result = await subagent.respond(
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 700, in respond
    sql_query = await self._create_valid_sql(messages, system_prompt, tables_to_source, step_title)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 110, in async_wrapper
    raise e

  File "/Users/ahuang/repos/lumen/lumen/ai/utils.py", line 104, in async_wrapper
    output = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/ahuang/repos/lumen/lumen/ai/agents.py", line 501, in _create_valid_sql
    if step.failed_title.startswith("Cancelled"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'startswith'
```
<img width="1514" alt="Image" src="https://github.com/user-attachments/assets/97fb03d9-5c05-4c28-843c-b7fc697fb96f" />

The loading spinner doesn't stop

**Comment by ahuang11** [comment]
Nevermind, was using old Lumen main

**Comment by ahuang11** [comment]
If all the SQL fails:

<img width="684" alt="Image" src="https://github.com/user-attachments/assets/391888a5-c9fa-4d71-91f0-1bd5b7eb696c" />

**Comment by ahuang11** [comment]
Eh still using old one :|
